version: "3.8"
services:
  web:
    build: ./app
    image: 439126960982.dkr.ecr.us-east-2.amazonaws.com/myfitness_app:myfitness_app_web
    command: gunicorn myfitness_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=myfitness_app_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=fitness-app.cawdmgpvjtyd.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-3-13-60-46.us-east-2.compute.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 439126960982.dkr.ecr.us-east-2.amazonaws.com/myfitness_app:myfitness_app_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
