# Generated by Django 3.2.2 on 2022-10-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('age', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Non-Binary')], null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
