# Generated by Django 3.2.2 on 2022-10-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('start_weight_lbs', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('goal_weight_lbs', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('water_goal_oz', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('exercise_goal_hrs', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=3, null=True)),
                ('calories_goal', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=5, null=True)),
                ('protein_goal_g', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('carbs_goal_g', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('fat_goal_g', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
            ],
        ),
    ]
