# Generated by Django 3.2.2 on 2022-10-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_desc', models.CharField(max_length=30, unique=True)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('carbs_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sugar_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gm_wt_1', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wt_desc_1', models.CharField(max_length=50)),
                ('gm_wt_2', models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True)),
                ('wt_desc_2', models.CharField(max_length=50)),
            ],
        ),
    ]
